### ISSUE TITLE
[upgrade django4.2]: Replace NullBooleanField by BooleanField with null=True.

### ISSUE THREAD

**Issue by awais786** [openedx/edx-enterprise#1766]
Few fields are using NullBooleanField which need upgrade
https://github.com/search?q=repo%3Aopenedx%2Fedx-enterprise%20NullBooleanField&type=code

https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0

**Comment by saleem-latif** [comment]
@awais786 All occurrences of `NullBooleanField` have been replace by `BooleanField` in https://github.com/openedx/edx-enterprise/pull/1794
